// <auto-generated />
using System;
using BaratoInventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaratoInventory.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924143004_AddImageUrlToProduct")]
    partial class AddImageUrlToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaratoInventory.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Beverages",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=150&q=80",
                            IsDeleted = false,
                            Name = "Coke 1.5L",
                            Price = 65.00m,
                            Quantity = 100,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 2,
                            Category = "Bakery",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=150&q=80",
                            IsDeleted = false,
                            Name = "Gardenia Classic White Bread",
                            Price = 75.00m,
                            Quantity = 50,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 3,
                            Category = "Dairy",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=150&q=80",
                            IsDeleted = false,
                            Name = "Alaska Fresh Milk 1L",
                            Price = 95.00m,
                            Quantity = 30,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 4,
                            Category = "Canned Goods",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?w=150&q=80",
                            IsDeleted = false,
                            Name = "Century Tuna Flakes in Oil",
                            Price = 35.00m,
                            Quantity = 200,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 5,
                            Category = "Snacks",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=150&q=80",
                            IsDeleted = false,
                            Name = "Piattos Cheese 85g",
                            Price = 38.00m,
                            Quantity = 150,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 6,
                            Category = "Household",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=150&q=80",
                            IsDeleted = false,
                            Name = "Ariel Powder 1kg",
                            Price = 250.00m,
                            Quantity = 45,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 7,
                            Category = "Household",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=150&q=80",
                            IsDeleted = false,
                            Name = "Joy Dishwashing Liquid 500ml",
                            Price = 110.00m,
                            Quantity = 80,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 8,
                            Category = "Beverages",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=150&q=80",
                            IsDeleted = false,
                            Name = "Nescafé Classic 200g",
                            Price = 155.00m,
                            Quantity = 120,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 9,
                            Category = "Frozen",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1619740455993-9e612b1af08a?w=150&q=80",
                            IsDeleted = false,
                            Name = "Purefoods Tender Juicy Hotdog 1kg",
                            Price = 320.00m,
                            Quantity = 60,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 10,
                            Category = "Condiments",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=150&q=80",
                            IsDeleted = false,
                            Name = "Datu Puti Soy Sauce 1L",
                            Price = 45.00m,
                            Quantity = 300,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 11,
                            Category = "Condiments",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1624823183493-6e3e13467645?w=150&q=80",
                            IsDeleted = false,
                            Name = "Mang Tomas Sarsa 330g",
                            Price = 55.00m,
                            Quantity = 140,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 12,
                            Category = "Canned Goods",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=150&q=80",
                            IsDeleted = false,
                            Name = "Ligo Sardines in Tomato Sauce 155g",
                            Price = 22.00m,
                            Quantity = 500,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 13,
                            Category = "Beverages",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=150&q=80",
                            IsDeleted = false,
                            Name = "Kopiko Blanca Twin Pack",
                            Price = 15.00m,
                            Quantity = 400,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 14,
                            Category = "Noodles",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=150&q=80",
                            IsDeleted = false,
                            Name = "Lucky Me! Pancit Canton Kalamansi",
                            Price = 18.00m,
                            Quantity = 600,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 15,
                            Category = "Meat",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=150&q=80",
                            IsDeleted = false,
                            Name = "Bounty Fresh Whole Chicken",
                            Price = 180.00m,
                            Quantity = 25,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 16,
                            Category = "Dairy",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=150&q=80",
                            IsDeleted = false,
                            Name = "Magnolia Gold Butter 200g",
                            Price = 125.00m,
                            Quantity = 40,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 17,
                            Category = "Snacks",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=150&q=80",
                            IsDeleted = false,
                            Name = "Pringles Original 149g",
                            Price = 105.00m,
                            Quantity = 85,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 18,
                            Category = "Personal Care",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1559591937-e62fb330bc1f?w=150&q=80",
                            IsDeleted = false,
                            Name = "Colgate Double Action Toothbrush",
                            Price = 65.00m,
                            Quantity = 110,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 19,
                            Category = "Personal Care",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1607006314177-3e3cfa0d7a04?w=150&q=80",
                            IsDeleted = false,
                            Name = "Safeguard Pure White Soap 130g",
                            Price = 45.00m,
                            Quantity = 250,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 20,
                            Category = "Snacks",
                            CreatedAtUtc = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=150&q=80",
                            IsDeleted = false,
                            Name = "Fita Crackers 250g",
                            Price = 55.00m,
                            Quantity = 90,
                            RowVersion = new byte[0]
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
